use utf8;

our %bt = (
       "article" => "定期刊行物または雑誌の論説記事(article)",
       "inproceedings"=> "会議の予稿集に収録の論文(inproceedings)",
       "book"=> "出版者が明確な書籍(book)",
       "incollection"=> "書籍の一部でそれ自身に表題(incollection)",
       "inbook"=> "書籍の一部で1つの章または範囲(inbook)",
       "manual"=> "技術文書(manual)",
       "booklet"=> "出版社やスポンサーのない本(booklet)",
       "masterthesis"=> "修士論文(masterthesis)",
       "phdthesis"=> "博士論文(phdthesis)",
       "proceedings"=> "会議の予稿集(proceedings)",
       "techreport"=> "技術報告集(techreport)",
       "unpublished"=> "未公刊(unpublished)",
       "misc"=> "その他(misc)"
       );

#%viewMenu = (
#    "list"=>"<img src=\"css/img/vm-list.png\">",
#    "table"=>"<img src=\"css/img/vm-table.png\">",
#    "latex"=>"<img src=\"css/img/vm-latex.png\">",
#    "add"=>"<img src=\"css/img/vm-add.png\">",
#    "edit"=>"<img src=\"css/img/vm-edit.png\">",
#    "delete"=>"<img src=\"css/img/vm-delete.png\">",
#    );
our %viewMenu = (
    "list"=>"リスト",
    "table"=>"　表　",
    "latex"=>"LaTeX",
    "add"=>"追　加",
    "edit"=>"編　集",
    "delete"=>"削　除",
    );

#%topMenu = (
#    "simple"=>"<img src=\"css/img/tm-simple.png\">",
#    "detail"=>"<img src=\"css/img/tm-detailed.png\">",
#    "japanese"=>"<img src=\"css/img/tm-japanese.png\">",
#    "english"=>"<img src=\"css/img/tm-english.png\">",
#    "login"=>"<img src=\"css/img/tm-login.png\">",
#    "logout"=>"<img src=\"css/img/tm-logout.png\">",
#    "config"=>"<img src=\"css/img/tm-config.png\">",
#    "help"=>"<img src=\"css/img/tm-help.png\">",
#    );
our %topMenu = (
    "simple"=>"簡易",
    "detail"=>"詳細",
    "japanese"=>"日本語",
    "english"=>"英語",
    "login"=>"ログイン",
    "logout"=>"ログアウト",
    "category"=>"分類設定",
    "config"=>"オプション設定",
    "help"=>"ヘルプ",
    );

our %msg = (
	"texname" => "名前",
	"texaffi" => "所属",
	"textitl" => "肩書",
	"texnme" => "名前を入力",
	"texaff" => "所属を入力",
	"texttl" => "肩書を入力",
	"needederr" => "必須フィールドが入力されていません．<br>ブラウザの戻るボタンで戻って入力をやり直してください．<br>なお，miscスタイルでも「タイトル」は必須です．",
	"category" => "分類",
	"addcat" => "分類追加",
	"delcat" => "分類削除",
	"rencat" => "分類名変更",

	"ordcat" => "分類順序変更",
	"ordercat" => "新しい分類の順序を指定",
        "chgord" => "順序変更",
        "catname" => "分類",
        "order" => "順序",
        "neworder" => "新しい順序(整数で入力)",

	"namenewcat" => "新しい分類名",
	"selectdelcat" => "削除する分類名を選択",
	"selectmovcat" => "削除する分類に含まれるデータの移動先を選択",
	"selectcat" => "分類名を選択",
	"del" => "削除",
	"add" => "追加",
	"efile" => "論文電子ファイル",
        "ed" => "編",
	"save" => "保 存",
	"makePDF" => "PDF",
	"listPDF" => "業績リストPDF",
	"editcat" => "分類編集",
	"uploadfile" => "アップロードするファイルを指定",
	"doEdit" => "更新",
	"selectType" => "文献型を選択",
	"editContents" => "内容編集",
	"addNew" => "新規登録",
	"import" => "インポート",
	"export" => "エクスポート",
	"imex" => "インポート/エクスポート",
	"langconf"=>"言語設定",
	"japanese"=>"日本語",
	"english"=>"英語",
	"all"=>"全て",
	"author"=>"著者",
	"1stauthor"=>"筆頭著者",
	"title"=>"タイトル",
	"publish"=>"論文誌/会議名",
	"year"=>"出版年",
	"filter"=>"検索",
	"found"=>"件の該当がありました．",
	"ascend" => "年月昇順",
	"descend" => "年月降順",
	"t_ascend" => "年月昇順(分類別)",
	"t_descend" => "年月降順(分類別)",
	"y_t_ascend" => "年月昇順(年，分類別)",
	"y_t_descend" => "年月降順(年，分類別)",
	"ffdetail" => "詳細",       
	"ffsimple" => "簡易",       
	"URL" => "このページのURL",
	"detailviewTitle"=>"業績データ詳細表示",
	"editTitle"=>"業績データ編集",
	"addTitle"=>"業績データ追加",
	"configTitle"=>"環境設定",
	"importTitle"=>"業績データインポート",
	"neededErrorTitle"=>"必須項目未入力エラー",
	"askPasswdTitle"=>"編集用パスワード入力",
	"askPasswd"=>"編集用パスワードを入力してください:",
	"auth"=>"認証",

        "faccess"=>"管理者のみ閲覧可能",
        "filedesc"=>"ファイルの説明",
        "open"=>"[一般閲覧可]",
        "hidden"=>"[一般閲覧不可]",

	#Add by Manabe
	"clrcookie"=>"Cookie初期化",
	"misc"=>"その他",

	"need" => "[必須]",
	"altneed" => "[どちらか必須]",

        "accepted" => "(採録済)",
        "submitted" => "(投稿中)",

	"Head_address" => "出版社住所 (address)",
	"Exp_address" => "出版社の住所を記す．",
	"Head_annote"=>"注釈 (annote)",
	"Exp_annote"=>"注釈を記す．",
	"Head_author"=>"著者名 (author)",
	"Exp_author"=>"著者名(複数の場合は半角カンマ\",\"または\" and \"で区切る．)を記す．",
	"Head_author_e"=>"英文著者名 (author)",
	"Exp_author_e"=>"authorが英語以外の場合，英文著者名を記す．",
	"Head_abstract"=>"内容梗概 (abstract)",
	"Head_booktitle"=>"書籍・会議録表題 (booktitle)",
	"Exp_booktitle"=>"一部が参照される書籍の表題を記す．",
	"Head_booktitle_e"=>"書籍・会議録表題(英文)",
	"Exp_booktitle_e"=>"booktitleが英語以外の場合，英文で書籍・会議録表題を記す．",
	"Head_chapter"=>"章番号 (chapter)",
	"Exp_chapter"=>"章の番号を記す．",
	"Head_edition"=>"版 (edition)",
	"Exp_edition"=>"書籍の版を記す．",
	"Head_editor"=>"編者名 (editor)",
	"Exp_editor"=>"編者名(複数の場合は半角カンマ\",\"または\" and \"で区切る．)を記す．",
	"Head_editor_e"=>"編者名 (英文)",
	"Exp_editor_e"=>"editorが英文以外の時，編者名を英文で記す．",
	"Head_howpublished"=>"刊行形式 (howpublished)",
	"Exp_howpublished"=>"規格外のものがどのように刊行されたかを記す．",
	"Head_institution"=>"発行元組織 (organization)",
	"Exp_institution"=>"技術報告の発行元組織",
	"Head_journal"=>"定期刊行物名 (journal)",
	"Exp_journal"=>"論文誌，学会誌などの誌名を記す．",
	"Head_journal_e"=>"定期刊行物名 (英文)",
	"Exp_journal_e"=>"journalが英文以外の時，誌名を英文で記す．",
	"Head_key"=>"キー (key)",
	"Exp_key"=>"(ローカルルール:英語フルネームで著者名を記す．著者名か英語著者名に英語フルネームが記入されていれば無くても良い．検索用．)",
	"Head_month"=>"刊行月 (month)",
	"Exp_month"=>"刊行された月を記す．",
	"Head_note"=>"付加情報 (note)",
	"Exp_note"=>"読者の役に立つような付加情報を記す．(ローカルルール: 国際会議の開催地をここに記述すると，リスト表示において末尾に付与される．)",
	"Head_number"=>"号数 (number)",
	"Exp_number"=>"定期刊行物，雑誌，技術報告書などの号数を記す．",
	"Head_organization"=>"組織名 (organization)",
	"Exp_organization"=>"会議のスポンサーになった組織を記す．",
	"Head_pages"=>"ページ範囲 (pages)",
	"Exp_pages"=>"ページ番号を記す．一般的に 000-111 の形で書く．",
	"Head_publisher"=>"出版元 (publisher)",
	"Exp_publisher"=>"",
	"Head_publisher_e"=>"出版元 (英文)",
	"Exp_publisher_e"=>"publisherが英文以外の時，出版元を英文で記す．",
	"Head_school"=>"学校名 (school)",
	"Exp_school"=>"学位論文が書かれた学校の名前を記す．",
	"Head_series"=>"シリーズ名 (series)",
	"Exp_series"=>"シリーズ名もしくは複数巻の書籍の総タイトルを記す．",
	"Head_style"=>"文献スタイル (\@〜)",
	"Exp_style"=>"文献のBiBTeXスタイル",
	"Head_title"=>"表題 (title)",
	"Exp_title"=>"文献の表題．リスト時のキャピタライズを防ぐには{...}で囲む．",
	"Head_title_e"=>"表題 (英文)",
	"Exp_title_e"=>"titleが英文以外の時，英文表題を記す．",
	"Head_type"=>"技術報告書の種別 (type)",
	"Exp_type"=>"",
	"Head_volume"=>"巻数 (volume)",
	"Exp_volume"=>"定期刊行物または全集の巻番号を記す．",
	"Head_year"=>"出版年 (year)",
	"Exp_year"=>"",
	"Head_acceptance"=>"採択率 (acceptance)",
	"Exp_acceptance"=>"会議の採択率を記す．",
	"Head_impactfactor"=>"Impact Factor (JCR)",
	"Exp_impactfactor"=>"インパクトファクターを記す．",
	"Head_bibent"=>"BiBTeXエントリ",
	"Head_url"=>"URL",
	"Exp_url"=>"この文献のURL",

	"volnum"=>"巻号",
	"ifacc"=>"JCR/採択率",
        "yearmonth"=>"出版年月",
         
        "Title_list"=>"研究業績リスト",
        "Title_table"=>"研究業績表",
        "Title_latex"=>"LaTeX用研究業績リスト",
        "Title_detail"=>"研究業績の詳細",
        "Title_edit"=>"研究業績の編集",
        "Title_add"=>"研究業績を追加",
        "Title_category"=>"分類の設定",

        "deleteConfirm"=>"この文献を削除してもよろしいですか？",

        "tags"=>"タグ",
        "filedelete"=>"ファイル削除",
        "fileDeleteConfirm"=>"このファイルを削除してもよろしいですか？",

        "showShortVN"=>"巻号を短く表示",
        "showAbbrev"=>"著者を略称で表示",
        "showUL"=>"検索著者に下線表示",
        "showJCR"=>"インパクトファクターなどを表示",
        "showNote"=>"開催地(note)を表示",

        "frequenttags"=>"この検索内の頻出タグ: ",

    "notavailable"=>"利用できません．",
    "nothingfound"=>"そのような文献が見つかりません．",

    "Title_config"=>"オプション設定",
    "tagsetting"=>"タグ設定",
    "tag_rebuild"=>"タグの再構築",
    "tag_rebuild_exp"=>"全文献のタグを表題から再構築します．現在のタグは全て失われます．",
    "rebuild"=>"再構築",

);

1;
